### ISSUE TITLE
Add header component

### ISSUE THREAD

**Issue by tombiddulph** [strakamichal/SemanticBlazor#23]
I'm not sure what the guidlines are around contributions as I can't find any. I've added a header component which can be found under this pr #19 please let me know what I need to do to get it merged.

**Comment by strakamichal** [comment]
Hi, I'm kind of newbie with open-source software and this type of collaboration. I will check your code and try to merge it into main branch. Thanks a lot for your contribution.

**Comment by strakamichal** [comment]
Your changes have been merged and released in version 1.6.7. Thanks a lot!
